name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Every day at midnight
  push:
    branches:
      - main  # Or your default branch

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub contribution grid snake
        uses: Platane/snk@v3
        with:
          github_user_name: kalhara2000
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      - name: Push to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
